### ISSUE TITLE
Update NumPy API

### ISSUE THREAD

**Issue by rocketinventor** [maxpumperla/betago#17]
Whenever I run `pip install betago` I get an error the error text: `#warning "Using deprecated NumPy API, disable it by " \` which shows up many times right before everything freezes.

The API usage should be updated.

**Comment by maxpumperla** [comment]
Hey @rocketinventor, could you please be a bit more specific about your error message? For instance, I know the warning pops up on some systems when installing h5py. Did you properly install hdf5 before, as explained in the readme? When does it freeze? Do you see any errors, too?

**Comment by rocketinventor** [comment]
@maxpumperla I followed all the instructions in the readme. I also followed instructions from #9 #1.
If I recall correctly, I was trying to install the dependencies manually so maybe it was a problem with `pip install -U scipy`. The dependency should have been auto fetched, though.

**Comment by macfergus** [comment]
@rocketinventor can you share the pip log? Try installing with `pip install --log install.txt betago` and then share the `install.txt` file

It would also help to know:
- OS and version
- Python / pip / setuptools version
- whether you are using a virtualenv

**Comment by rocketinventor** [comment]
Interestingly enough, this time it auto fetched the dependencies. Still froze at the same place, though. Here is the log file: [install.txt](https://github.com/maxpumperla/betago/files/276161/install.txt)

I am using c9.io, virtual Ubuntu. I don't know which version numbers, though.

**Comment by macfergus** [comment]
Hi @rocketinventor, thanks for all the details.

I updated the readme: https://github.com/maxpumperla/betago/commit/be14775b9e19bfdde41caacb2620935a4637cdf8 Please try the new steps and let us know if it works for you.

The original install instructions were written for Ubuntu vivid. Cloud9 runs Ubuntu trusty, so we need to upgrade a few things first.

BTW, cloud9 machines are relatively slow and it took over 20 minutes for me to install everything. So if seems frozen, be patient, it's probably just compiling...

**Comment by rocketinventor** [comment]
The new instructions seemed to do the trick

**Comment by rocketinventor** [comment]
How do I see the interface once the server is up?
