### ISSUE TITLE
Tips for using c9.io

### ISSUE THREAD

**Issue by rocketinventor** [maxpumperla/betago#18]
Hi, I was able to get the python code for c9 working but it auto-opens in lynx and I cannot figure out how to play the demo.
Any tips?

**Comment by macfergus** [comment]
Hi, the problem is that the html and javascript are served as local file:// URLs. So you can't access them over the network. We should serve them through the web server to fix this.

To do this, we need to configure the flask `static_folder` to point to a path containing `demoBot.html` `jgboard-latest.js` and `board.js`. Then update the `postMove` URL to be relative instead of absolute.

PS. @rocketinventor, if you are interested in contributing to betago this would be a really useful and straightforward place to start :)

**Comment by rocketinventor** [comment]
I'm still working on getting flask to serve the files statically. My current efforts are not working though. It looks something like [this](https://github.com/maxpumperla/betago/files/285894/diff.txt) and is based in part on [this guide](https://codepen.io/asommer70/post/serving-a-static-directory-with-flask) b/c I didn't understand [this one](http://flask.pocoo.org/snippets/102/). Workspace url: https://ide.c9.io/rocketinventor/beta-go

The `postMove` URL part is done, though, I'll push it out when I get the flask server running.

P.s. @macfergus Thanks for helping me get started 👍

**Comment by macfergus** [comment]
Your diff looks good, I think the only thing you're missing is to change
`app = Flask(__name__)`
to
`app = Flask(__name__, static_folder='../ui')`
or something like that. All the calls to `send_static_file` and such are relative to `static_folder`.

Thanks for tackling this!

**Comment by rocketinventor** [comment]
After several moths of inactivity, I finally noticed that the C9 IDE documentation says explicitly that you can only use ports `8080 - 8082`.

I'm going to take another look to see if that was my problem.

**Comment by maxpumperla** [comment]
Great to hear! Let me know if it solved your problem. Haven't had time to work on betago for a very long time either...

**Comment by rocketinventor** [comment]
@maxpumperla No luck so far.
I can't even get it to work in curl:
```
rocketinventor:~/workspace/betago (master) $ curl 0.0.0.0:8081/prediction                                                                                 
curl: (7) Failed to connect to 0.0.0.0 port 8081: Connection refused
rocketinventor:~/workspace/betago (master) $ curl 0.0.0.0:5000/prediction
curl: (7) Failed to connect to 0.0.0.0 port 5000: Connection refused
rocketinventor:~/workspace/betago (master) $ curl localhost:5000/prediction
curl: (7) Failed to connect to localhost port 5000: Connection refused
```

[Here is the traceback from flask](https://github.com/maxpumperla/betago/files/704644/predictionlog.txt) (change the ext to .html)

Files:
https://c9.io/rocketinventor/beta-go/files/betago

**Comment by rocketinventor** [comment]
Any chance this is related to #21?

**Comment by rocketinventor** [comment]
@maxpumperla Everything works now! Please merge #28 so that others can benefit as well.

**Comment by rocketinventor** [comment]
#28 also contains a bash script that makes running the demo easier. Soon, it will be super simple to run anywhere (especially c9.io).
