### ISSUE TITLE
error test : zipfile.BadZipfile: File is not a zip file

### ISSUE THREAD

**Issue by nanxintin** [maxpumperla/betago#19]
I was very interested in AlphaGo, and luckily I found the BetaGo. When I try to understand the working mechanism of the bot, I came across some problems  when running some demos in the examples fold, such as "end_to_end.py", "train_and_store.py","train_generator.py". The error is as follows:
"total num games: 179695
Drawn 1000 samples:

> > > Number of zip files: 103
> > > Traceback (most recent call last):
> > >   File "train_generator.py", line 40, in <module>
> > >     data_generator = processor.load_go_data(num_samples=args.sample_size)
> > >   File "/home/sk/.betago/local/lib/python2.7/site-packages/betago/dataloader/base_processor.py", line 132, in load_go_data
> > >     self.map_to_workers(name, samples)
> > >   File "/home/sk/.betago/local/lib/python2.7/site-packages/betago/dataloader/base_processor.py", line 219, in map_to_workers
> > >     results = p.get(0xFFFF)
> > >   File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
> > >     raise self._value
> > > zipfile.BadZipfile: File is not a zip file"
> > > Unfortunately, I had difficulty to solve this problem. I would be much grateful if you could give me some advice.

**Comment by cdmalon** [comment]
I think pull request #25 fixes this problem.

**Comment by maxpumperla** [comment]
@nanxintin does this problem still persist? I think this should be fixed. I'm closing for now, feel free to re-open if necessary. Thanks!
