### ISSUE TITLE
How can I run it on windows

### ISSUE THREAD

**Issue by jason19659** [maxpumperla/betago#20]
How can I run it on windows?

**Comment by rocketinventor** [comment]
Try using [Cygwin](https://www.cygwin.com/). Install it on your system, then proceed to follow the instructions as if using Linux.

**Comment by rocketinventor** [comment]
@jason19659 Any luck?

**Comment by rocketinventor** [comment]
@comp0ker Have you tried running this on your laptop, yet?

**Comment by rocketinventor** [comment]
@comp0cker have you tried running this yet? Any luck?

**Comment by maxpumperla** [comment]
@jason19659 I'm working on dockerizing the application, which should make it easy to run on Windows as well.

**Comment by maxpumperla** [comment]
Betago demo is now dockerized, should work on any platform. See the readme for more info @jason19659 @rocketinventor.

Closing this now. Let me know if you see anything missing.
