### ISSUE TITLE
Make AJAX asynchronous

### ISSUE THREAD

**Issue by rocketinventor** [maxpumperla/betago#22]
A quick look at the source code reveals that the requests to the server are being handled asynchronously. This can lock up the page and is bad for performance (and Karma).

The JS should be rewritten to work asynchronously.

**Comment by rocketinventor** [comment]
The current handling can cause bugs.
Steps:

1. Open Betago
2. Open debug tools on browser and set it to simulate a slow network
3. Quickly click on a few open spots (before the client finishes handling the first one

In my test, I clicked on three spaces in the same column. Inside the client, it looks how I expect. However, if you look at the log (last three requests) you can see that the client is misinforming the server on which moves were made. This is likely a (partial) cause of issue #27.

![image](https://cloud.githubusercontent.com/assets/6473114/23340078/130c7448-fbfe-11e6-968f-31e5e18f2bfc.png)

![image](https://cloud.githubusercontent.com/assets/6473114/23340091/7f844d08-fbfe-11e6-9266-f5257ee20f19.png)

**Comment by maxpumperla** [comment]
This looks like a fair concern @rocketinventor, why did you close this issue?
