### ISSUE TITLE
Main theory behind

### ISSUE THREAD

**Issue by zxzhijia** [maxpumperla/betago#3]
Thank you for sharing first. So in other words, it use only DNN to predict the next move other than AlphaGo, which used also the Monte Carlo Tree Search combined with DNNs.

**Comment by maxpumperla** [comment]
Yes, right now it only uses 'policy networks' trained by, for instance, convolutional neural networks. My hope is that someone (might be me) will be implementing the second step (MC tree search) as well. The interface for a go bot in betago is very flexible, so this is just a first step.

Try to see betago more as a platform with which to build your own Go AI than a tool to just run.

**Comment by EderSantana** [comment]
this might be a good reference to start with https://jeffbradberry.com/posts/2015/09/intro-to-monte-carlo-tree-search/

**Comment by zxzhijia** [comment]
Thank you for that reference. I'll read it. My understanding of the AlphaGo
paper is that Deep neural networks are used for replacing the random
sampling step of MCTS, which is the main part. I'm interested in help
improving your code.

**Comment by zxzhijia** [comment]
Is the one you trained considered as supervised learning policy network or
reinforcement learning policy network?

**Comment by zxzhijia** [comment]
Thanks.

**Comment by maxpumperla** [comment]
Hey @EderSantana, that's a very nice introductory artice. You seem to be interested in Go as well, so I'm curious if I can convince you to contribute. :D

**Comment by EderSantana** [comment]
Yeah, I'm def planning to help. Although I've never really played go. I'm just finishing the base of an RL lib (beyond the common q-learn everybody is doing).

Did you implement the REINFORCE part already?

**Comment by maxpumperla** [comment]
That would be great. I have little experience with RL myself and no concrete plan to proceed, but @macfergus indicated that he might also be interested in implementing that. Any help is much appreciated!

**Comment by maxpumperla** [comment]
cc/ @EderSantana https://github.com/maxpumperla/betago/pull/7

**Comment by bhack** [comment]
See also keras effort at https://github.com/Rochester-NRT/AlphaGo

**Comment by maxpumperla** [comment]
Man, @bhack, you're everywhere. Thanks, I didn't know about that project.

**Comment by maxpumperla** [comment]
@zxzhijia did we discuss this issue to your satisfaction? Would you want us to maintain a wiki page on methodology? Anything else for now?

**Comment by zxzhijia** [comment]
Hi Max, my problem is solved. Thank you.
