### ISSUE TITLE
JS error handling [improvements needed]

### ISSUE THREAD

**Issue by rocketinventor** [maxpumperla/betago#30]
I have noticed that if the server responds with any type of error, the client `demobot.html` **freaks out**. When this happens, no move is processed for white and the client switches to playing white for one (1) move. At this point, the player can only play in areas that white is allowed to play in, and locally, their moves count for white. However, the moves are still recorded and sent to the server as moves made by black.

There is currently no way to update the board with the server and there is no way (that I know of) to undo the last move (easily). The only way to avoid this issue (at this point) is to hold off actually making the move until the server resolves the move (successfully). Another option is that every time a move is made, a "snapshot" could be recorded before it is processed (and restored if it causes an error). 

This lack of error handling is the partial cause for the symptoms described in #29, #26, and #27.

**Comment by macfergus** [comment]
I propose splitting the /predict HTTP command into two operations: one to play the human move, and a second to generate the bot move

Then the client flow could be:
1. Make the server request to apply the human move
2. Wait for request to finish successfully (should be fast)
3. Update client state and draw the human move
4. Make a server request for a bot move (could be slow, with a more sophisticated bot engine)
5. Update client state and draw bot move

(Optimistic update with error handling might be nice for a production-quality client, but for the demo client I think blocking is fine)

**Comment by rocketinventor** [comment]
While splitting the request may be a good idea, I don't think that it would help solve the problem. If the bot has an error, we will still have a problem. Also, the additional level of complexity is not worth it. I'd rather have a separate request for getting a copy of the game _from the server_.

If we did go the route of splitting the request, it might make more sense to use web-sockets.
The client flow would then look like this:

Upon starting:
---
**The client can either choose to join an in-progress game _or_ to start a new one.**

1. Open socket connection with server
  a. Optionally: collect more data (i.e. username)
2. Check if a game is in progress. Then do one of the following:
  a. Ask for a copy of the game data
  b. Start a new game instance (with default settings) _or_
  c. Notify server of non-default_preferences_ (see #6 for ideas), _then_ start a new game instance
3. Join the chosen game session/instance
4. Receive copy of current game state (if in progress)

During a game session:
---
1. Update server with human move color and coordinates
2. Wait for a confirmation from the server
4. Draw human move
5. Wait for the predicted move
6. Update client state and draw move

The benefit of this route is that the server could be programmed to _mirror_ the current game across all _open web clients_. In this scheme, step 1 is _optional_! All the other steps (2 - 6) can happen concurrently on a (hypothetically) infinite amount of clients with one _or all_ of them able to pick the next move.

**Comment by rocketinventor** [comment]
I think the best route to go is to draw the stone but not run `jboard.setType(playNext.captures, JGO.CLEAR)` (clear opponent's stones) until a success is recorded from the server. If there is an error, the stone should be removed.

**Comment by rocketinventor** [comment]
It's worth noting that moves are getting sent to the server, even if they are invalid.

**Client-side log:**
![image](https://cloud.githubusercontent.com/assets/6473114/23339473/4ab26fea-fbf1-11e6-8304-6abb4f8fd3a1.png)

**Comment by rocketinventor** [comment]
Additionally, the next move after an invalid (but server-accepted) move is _usually_ ignored but, sometimes it is evaluated as a black move.

Please see the below diagram below. The black box is where I attempted to play and the white box is the play that the server responded with.

![image](https://cloud.githubusercontent.com/assets/6473114/23340191/1e2dd2b6-fc00-11e6-8f10-cbcc1cbd7266.png)
As you can see, both moves were accepted by the server but rejected by the client.
![image](https://cloud.githubusercontent.com/assets/6473114/23340203/500b5ac4-fc00-11e6-8e83-13432a845dfb.png)

The rest of the time, the response from the server is silently dropped.

**Comment by macfergus** [comment]
> I think the best route to go is to draw the stone but not run jboard.setType(playNext.captures, JGO.CLEAR) (clear opponent's stones) until a success is recorded from the server. If there is an error, the stone should be removed.

Yes this is a good plan.

Just to clarify what I was saying about splitting the `/predict` call:

1. The client should check move validity with the server. If the server rejects a move, the client should not update the board (and instead should re-sync the game state, probably).
2. But the bot may be slow to generate its next move. It would be a bad experience if the human player had to wait 10 - 20 seconds to see their move on the board. (Thinking ahead to a more sophisticated version of the bot.)
3. Splitting the request means we can confirm the move quickly, and the user will see the board updated after just a few ms.
4. Splitting the request makes the HTTP protocol more similar to GTP. (In fact, we could consider some kind of GTP-over-HTTP scheme.)

Using web sockets to sync state across multiple browser tabs seems like overkill to me, but if that's what interests you, by all means go for it :)

Supporting full sync of game state from the server is a good idea in any case.

**Comment by rocketinventor** [comment]
I am going to go ahead and close this issue due to the improvements of pull request #38 which address the  actual issue of poor client side handling. The rest of this thread, which is about sync mechanisms, should be given its own issue for discussion as it is off topic.

If anyone else notices new problems with the _javascript error handling_, they should feel free to re-open this thread.
