### ISSUE TITLE
pip install betago fails with problems with numpy, I gess

### ISSUE THREAD

**Issue by kaluosi** [maxpumperla/betago#9]
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DH5_USE_16_API -I/tmp/pip-build-stypprco/h5py/lzf -I/opt/local/include -I/usr/local/include -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c /tmp/pip-build-stypprco/h5py/h5py/defs.c -o build/temp.linux-x86_64-3.4/tmp/pip-build-stypprco/h5py/h5py/defs.o
    In file included from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                     from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from /tmp/pip-build-stypprco/h5py/h5py/api_compat.h:26,
                     from /tmp/pip-build-stypprco/h5py/h5py/defs.c:303:
    /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    In file included from /tmp/pip-build-stypprco/h5py/h5py/defs.c:303:0:
    /tmp/pip-build-stypprco/h5py/h5py/api_compat.h:27:18: fatal error: hdf5.h: No such file or directory
     #include "hdf5.h"
                      ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by maxpumperla** [comment]
Could I please refer you to #2 which is essentially the same problem?

**Comment by ddugovic** [comment]
I suggest starting with [this comment](https://github.com/maxpumperla/betago/issues/2#issuecomment-210715880) and working your way up to the top comment, in the hopes that you suffer less than I did!

**Comment by maxpumperla** [comment]
Well, we have to find a way to document this properly. This is clearly an issue with installing scipy stack prior to h5py on linux, not betago itself. If it doesn't work with pip, that is unfortunate, but given the amount of SO and github issues on this topic, there doesn't seem to be an easy way out.

@ddugovic @kaluosi what would you like to see? I'd propose to link to a comment section in the main README.md, but I'm open for suggestions.

**Comment by maxpumperla** [comment]
@macfergus what's your take on such matters?

**Comment by ddugovic** [comment]
I'd like to see a complete dependency list, plus some suggestions of how to obtain said dependencies.

**Comment by macfergus** [comment]
I updated the README with more detailed instructions for Ubuntu/Debian type platforms (https://github.com/maxpumperla/betago/commit/f010cb1499216f18dd4471a34fc1416b3efd4322)

I'll try to do the same for Mac OS a little later.

@ddugovic @kaluosi do these help? Any other platforms you'd like to see?

Also, would it be crazy to provide a Vagrantfile that installs all the deps? A Vagrant is probably too slow for training, but it should be fine if someone just wants to run bots.

**Comment by maxpumperla** [comment]
@ddugovic @kaluosi we added instructions for Mac as well, are you OK with this?

@macfergus sure, why not? Docker would be nice as well.

**Comment by ddugovic** [comment]
@macfergus Thanks, that's excellent!  I just upgraded to Ubuntu 16 and this solution exceeds my expectations!

I'm not a Mac OS user, but the more the merrier...

**Comment by flakeman2** [comment]
I'm using Ubuntu 15.10 and had to manually install these packages in order for 'pip install betago' to work:

sudo apt-get install python-matplotlib python-scipy python-numpy libatlas-base-dev libatlas-dev libatlas3-base libblas-dev liblapack-dev

Devin

**Comment by rocketinventor** [comment]
@flakeman2 I followed all the instructions but, I keep getting this error:
`Traceback (most recent call last):
  File "run_demo.py", line 2, in <module>
    import yaml
ImportError: No module named yaml
`

I'm using c9.io https://ide.c9.io/rocketinventor/beta-go

**Comment by rocketinventor** [comment]
@maxpumperla 
I had had to install many dependencies by hand and it still doesn't work.
Such as:
`pip install pyaml`

`pip install keras`

`pip install -U flask-cor`

`pip install -U scipy` or `apt-get install scipy`

**Comment by maxpumperla** [comment]
guys, I'm not sure what the status on this is, but it might be worth looking into the new `Dockerfile` as a reference for how to install betago "from scratch".

**Comment by maxpumperla** [comment]
I will close this for now, not sure if it helps to keep this alive. We now have a lot of documentation that explains how to install, including a Docker demo.
